//! Registration keys, machine activation, and entitlements.
//!
//! Keys are Ed25519-signed by Daemon Labs' issuer key (see the
//! `readactus-keygen` tool, which is never shipped to users); the app
//! embeds only the PUBLIC verifying key, so keys can be verified fully
//! offline and cannot be forged without the issuer secret.
//!
//! Activation binds a verified key to THIS machine's fingerprint in the
//! local activation store. On every subsequent run the fingerprint is
//! re-checked: an activation file copied to a different machine refuses
//! to load. Honest limitation, by design and documented: offline
//! node-locking stops casual key sharing, but detecting the same key
//! activated independently on two machines requires a server-side
//! activation registry — the structure here (key id, fingerprint) is
//! exactly what that server will record when it exists.

use std::path::PathBuf;

use data_encoding::BASE32_NOPAD;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;

/// Free-tier extraction ceiling: 50 MB, hard. The metering stream in
/// readactus-core aborts the run the moment the NEXT row would cross it.
pub const FREE_TIER_EXTRACT_CAP_BYTES: u64 = 50 * 1024 * 1024;

/// Daemon Labs issuer public key (base32). Generated by
/// `readactus-keygen init`; the matching secret key never leaves the
/// issuing machine and is never committed.
pub const ISSUER_PUBLIC_KEY_B32: &str = "PBFJVXIKWNQS4HQC6LRSJO34ANZOZDZM7C3PSS4DACDWC7WGY4DA";

const KEY_PREFIX: &str = "RDX1";

#[derive(Debug, Error)]
pub enum LicenseError {
    #[error("malformed registration key: {0}")]
    Malformed(String),
    #[error("registration key signature is invalid — key was not issued by Daemon Labs or was altered")]
    BadSignature,
    #[error("this registration key is activated on a different computer")]
    MachineMismatch,
    #[error("activation store error: {0}")]
    Store(String),
}

/// What a license entitles the holder to. Everything the pipeline gates
/// on lives here — the rest of the app never inspects keys directly.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entitlements {
    /// Hard ceiling on bytes extracted from a source per run. `None` =
    /// unlimited.
    pub max_extract_bytes: Option<u64>,
    /// Whether this entitlement set came from a registered key.
    pub registered: bool,
}

impl Entitlements {
    /// Unregistered default: 50 MB hard cap.
    pub fn free() -> Self {
        Self { max_extract_bytes: Some(FREE_TIER_EXTRACT_CAP_BYTES), registered: false }
    }

    /// Registered: unlimited extraction, node-locked to one machine.
    pub fn registered() -> Self {
        Self { max_extract_bytes: None, registered: true }
    }
}

/// The signed payload inside a registration key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyPayload {
    pub version: u8,
    pub key_id: String,
    pub tier: String,
}

/// A parsed, signature-verified registration key.
#[derive(Debug, Clone)]
pub struct RegistrationKey {
    pub payload: KeyPayload,
}

impl RegistrationKey {
    /// Parses and verifies `RDX1-<payload>-<signature>` against the
    /// embedded issuer public key. Verification is fully offline.
    pub fn verify(key_text: &str, issuer_public_key_b32: &str) -> Result<Self, LicenseError> {
        let key_text = key_text.trim();
        let mut parts = key_text.splitn(3, '-');
        let prefix = parts.next().unwrap_or_default();
        let payload_b32 = parts.next().ok_or_else(|| LicenseError::Malformed("missing payload".into()))?;
        let sig_b32 = parts.next().ok_or_else(|| LicenseError::Malformed("missing signature".into()))?;

        if prefix != KEY_PREFIX {
            return Err(LicenseError::Malformed(format!("expected {KEY_PREFIX} key, got '{prefix}'")));
        }

        let payload_bytes = BASE32_NOPAD
            .decode(payload_b32.as_bytes())
            .map_err(|e| LicenseError::Malformed(format!("payload encoding: {e}")))?;
        let sig_bytes = BASE32_NOPAD
            .decode(sig_b32.as_bytes())
            .map_err(|e| LicenseError::Malformed(format!("signature encoding: {e}")))?;

        let pubkey_bytes = BASE32_NOPAD
            .decode(issuer_public_key_b32.as_bytes())
            .map_err(|e| LicenseError::Malformed(format!("issuer public key encoding: {e}")))?;
        let pubkey_arr: [u8; 32] =
            pubkey_bytes.try_into().map_err(|_| LicenseError::Malformed("issuer public key length".into()))?;
        let verifying_key = VerifyingKey::from_bytes(&pubkey_arr).map_err(|_| LicenseError::BadSignature)?;

        let sig_arr: [u8; 64] = sig_bytes.try_into().map_err(|_| LicenseError::Malformed("signature length".into()))?;
        let signature = Signature::from_bytes(&sig_arr);

        verifying_key.verify(&payload_bytes, &signature).map_err(|_| LicenseError::BadSignature)?;

        let payload: KeyPayload =
            serde_json::from_slice(&payload_bytes).map_err(|e| LicenseError::Malformed(format!("payload: {e}")))?;
        Ok(Self { payload })
    }
}

/// A stable-ish fingerprint of this machine, hashed so the raw machine id
/// never appears in the activation file. Linux: /etc/machine-id.
/// Fallback: hostname-ish environment. (macOS/Windows identifiers get
/// added with the desktop builds for those platforms.)
pub fn machine_fingerprint() -> String {
    let raw = std::fs::read_to_string("/etc/machine-id")
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .or_else(|| std::env::var("HOSTNAME").ok())
        .or_else(|| std::env::var("COMPUTERNAME").ok())
        .unwrap_or_else(|| "unknown-machine".to_string());

    let mut hasher = Sha256::new();
    hasher.update(b"readactus-machine-v1");
    hasher.update(raw.as_bytes());
    let digest = hasher.finalize();
    BASE32_NOPAD.encode(&digest[..16])
}

/// What's stored on disk after activation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Activation {
    pub key_text: String,
    pub key_id: String,
    pub tier: String,
    pub machine_fingerprint: String,
    pub activated_at: String,
}

fn default_store_path() -> Result<PathBuf, LicenseError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| LicenseError::Store("no config directory on this platform".into()))?
        .join("readactus");
    Ok(dir.join("activation.json"))
}

/// Activates a key on THIS machine: verifies the signature, then records
/// the key against this machine's fingerprint.
pub fn activate(key_text: &str, issuer_public_key_b32: &str, store_path: Option<PathBuf>) -> Result<Activation, LicenseError> {
    let key = RegistrationKey::verify(key_text, issuer_public_key_b32)?;
    let activation = Activation {
        key_text: key_text.trim().to_string(),
        key_id: key.payload.key_id.clone(),
        tier: key.payload.tier.clone(),
        machine_fingerprint: machine_fingerprint(),
        activated_at: chrono_free_timestamp(),
    };

    let path = match store_path {
        Some(p) => p,
        None => default_store_path()?,
    };
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| LicenseError::Store(e.to_string()))?;
    }
    let json = serde_json::to_string_pretty(&activation).map_err(|e| LicenseError::Store(e.to_string()))?;
    std::fs::write(&path, json).map_err(|e| LicenseError::Store(e.to_string()))?;
    Ok(activation)
}

/// Loads the current entitlements: verified + fingerprint-matched
/// activation → registered; anything else → free tier. A present-but-
/// wrong-machine activation is an explicit error, not a silent downgrade,
/// so the user learns WHY they're not registered.
pub fn current_entitlements(issuer_public_key_b32: &str, store_path: Option<PathBuf>) -> Result<Entitlements, LicenseError> {
    let path = match store_path {
        Some(p) => p,
        None => default_store_path()?,
    };
    let contents = match std::fs::read_to_string(&path) {
        Ok(c) => c,
        Err(_) => return Ok(Entitlements::free()),
    };
    let activation: Activation =
        serde_json::from_str(&contents).map_err(|e| LicenseError::Store(format!("corrupt activation file: {e}")))?;

    // Re-verify the signature every load — an edited activation file is
    // just a free tier with extra steps.
    RegistrationKey::verify(&activation.key_text, issuer_public_key_b32)?;

    if activation.machine_fingerprint != machine_fingerprint() {
        return Err(LicenseError::MachineMismatch);
    }

    Ok(Entitlements::registered())
}

/// ISO-ish timestamp without pulling chrono into this crate.
fn chrono_free_timestamp() -> String {
    match std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH) {
        Ok(d) => format!("unix:{}", d.as_secs()),
        Err(_) => "unix:0".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};

    fn issue_test_key(signing: &SigningKey, tier: &str) -> String {
        let payload = KeyPayload { version: 1, key_id: "test-key-0001".into(), tier: tier.into() };
        let payload_bytes = serde_json::to_vec(&payload).unwrap();
        let sig = signing.sign(&payload_bytes);
        format!(
            "{KEY_PREFIX}-{}-{}",
            BASE32_NOPAD.encode(&payload_bytes),
            BASE32_NOPAD.encode(&sig.to_bytes())
        )
    }

    fn test_keypair() -> (SigningKey, String) {
        let signing = SigningKey::generate(&mut rand::rngs::OsRng);
        let pubkey_b32 = BASE32_NOPAD.encode(signing.verifying_key().as_bytes());
        (signing, pubkey_b32)
    }

    #[test]
    fn valid_key_verifies() {
        let (signing, pubkey) = test_keypair();
        let key_text = issue_test_key(&signing, "pro");
        let key = RegistrationKey::verify(&key_text, &pubkey).unwrap();
        assert_eq!(key.payload.tier, "pro");
    }

    #[test]
    fn tampered_payload_rejected() {
        let (signing, pubkey) = test_keypair();
        let key_text = issue_test_key(&signing, "pro");
        // Alter one payload character.
        let mut parts: Vec<String> = key_text.splitn(3, '-').map(String::from).collect();
        let mut chars: Vec<char> = parts[1].chars().collect();
        let i = chars.len() / 2;
        chars[i] = if chars[i] == 'A' { 'B' } else { 'A' };
        parts[1] = chars.into_iter().collect();
        let tampered = parts.join("-");
        assert!(RegistrationKey::verify(&tampered, &pubkey).is_err());
    }

    #[test]
    fn key_from_wrong_issuer_rejected() {
        let (other_signing, _) = test_keypair();
        let (_, real_pubkey) = test_keypair();
        let forged = issue_test_key(&other_signing, "pro");
        assert!(matches!(RegistrationKey::verify(&forged, &real_pubkey), Err(LicenseError::BadSignature)));
    }

    #[test]
    fn activation_roundtrip_grants_registered_entitlements() {
        let (signing, pubkey) = test_keypair();
        let key_text = issue_test_key(&signing, "pro");
        let dir = tempfile::tempdir().unwrap();
        let store = dir.path().join("activation.json");

        activate(&key_text, &pubkey, Some(store.clone())).unwrap();
        let ent = current_entitlements(&pubkey, Some(store)).unwrap();
        assert_eq!(ent, Entitlements::registered());
        assert_eq!(ent.max_extract_bytes, None);
    }

    #[test]
    fn no_activation_means_free_tier_cap() {
        let (_, pubkey) = test_keypair();
        let dir = tempfile::tempdir().unwrap();
        let ent = current_entitlements(&pubkey, Some(dir.path().join("missing.json"))).unwrap();
        assert_eq!(ent.max_extract_bytes, Some(FREE_TIER_EXTRACT_CAP_BYTES));
        assert!(!ent.registered);
    }

    #[test]
    fn foreign_machine_activation_rejected() {
        let (signing, pubkey) = test_keypair();
        let key_text = issue_test_key(&signing, "pro");
        let dir = tempfile::tempdir().unwrap();
        let store = dir.path().join("activation.json");
        let mut activation = activate(&key_text, &pubkey, Some(store.clone())).unwrap();

        // Simulate the file having been copied from another computer.
        activation.machine_fingerprint = "SOMEOTHERMACHINE".into();
        std::fs::write(&store, serde_json::to_string(&activation).unwrap()).unwrap();

        assert!(matches!(
            current_entitlements(&pubkey, Some(store)),
            Err(LicenseError::MachineMismatch)
        ));
    }
}
